#!/bin/bash

mkdir -p sel
mkdir -p img

../../NNC $1 $2 -1 &> sel/tmp.csv

Rscript --vanilla PlotVoronoi.R $2 2>>/dev/null

f=$(basename $2 .txt)
mkdir -p sel/$f
mkdir -p img/$f
mv sel/tmp.csv sel/$f/$1.csv
mv img/tmp.pdf img/$f/$1.pdf
